name: CI/CD Deploy

on:
  push:
    branches:
      - main   # 推送 main 就触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v3

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装 Yarn
        run: npm install -g yarn

      - name: 安装依赖
        run: yarn install --frozen-lockfile

      - name: 构建
        run: yarn build

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2